language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      
solution: FSharp.Interop.Compose.sln
    
mono: beta
dotnet: 2.0.3

install:
  - which msbuild
  - msbuild /ver

script:
  - ./build.fsx

branches:
  only:
    - master