image: Visual Studio 2017

configuration: Debug

environment:
  vsuffix: alpha$(APPVEYOR_BUILD_NUMBER)
  githubdeploy: false

install:
  - ps: nuget install FSharp.Compiler.Tools -ExcludeVersion -OutputDirectory extra

build: off

build_script:
  - cmd: set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\extra\FSharp.Compiler.Tools\tools\
  - cmd: fsi --exec ./build.fsx

test: off

artifacts:
  - path: '**\bin\*\*.nupkg'