os: Windows Server 2012

environment:
  EnableNuGetPackageRestore: true

build_script:
  - "set PATH=%PATH%;C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.0\\Framework\\v4.0\\"
  - fsi --exec build.fsx BuildTest

test:
  assemblies:
    - test\build\NET45\Test-NET45.dll
    - test\build\NET40\Test-NET40.dll
    - test\build\NET35\Test-NET35.dll
    - test\build\PORTABLE_47\Test-PORTABLE_47.dll
